apiVersion: v1
kind: ReplicationController
metadata:
 name: kubia2
spec:
 replicas: 3
 selector:
  app: kubia2
 template:
  metadata:
   labels:
    app: kubia2
  spec:
   containers:
   - name: kubia2
     image: luksa/kubia
     ports:
     - containerPort: 8080
